### ISSUE TITLE
use of Mojolicious?

### ISSUE THREAD

**Issue by nicolasfranck** [jhthorsen/json-validator#17]
Thanks for this module! It's quite complete.

The only thing I'm worried about, is the fact that it requires the whole Mojolicious stack.
Can one just use LWP::UserAgent and JSON(::XS) instead of Mojo::UserAgent and Mojo::JSON?
I'm sure Mojolicious uses similar packages in the background.

I never used Mojolicious, so I do not know the advantages.

**Comment by jhthorsen** [comment]
Why do you worry about the use of Mojolicious?

**Comment by nicolasfranck** [comment]
Mojolicious seems to me too big for this "simple" task: validating a schema.

**Comment by jhthorsen** [comment]
Just to comment on "the whole Mojolicious stack":

* Mojolicious is less than 10k of lines. That's really not a lot.
* LWP::UserAgent has these dependencies: https://widgets.stratopan.com/wheel?q=libwww-perl-6.15&fs=1 Notice that it also requires HTTP::Daemon. It also require me to write more code, since LWP::UserAgent is less DWIM.
* Mojo::JSON cannot be replaced, since the other JSON parses has (from my knowledge) no way to understand the difference between the string "42" and the number 42.
* Mojo::JSON::Pointer could probably be replaced by JSON::Pointer
* Mojo::Util::slurp could be replaced by File::Slurp

It's a bit more complicated than just validating the scheme, because of how it resolves ```$ref``` and being able to fetch files from ```__DATA__```, web and files.

But again: What is the real problem? I cannot discuss feelings. Please provide an objective reason for why I should not depend on Mojolicious.

I think installation time would even go up if I would depend on a bunch of other modules, which would not provide any more functionality.

**Comment by jhthorsen** [comment]
I forgot to comment on "similar packages in the background": Mojolicious is self contained, meaning that in recent versions of Perl you only need core dependencies. Mojo does not use LWP, nor HTTP::Tiny. In fact it would not be possible due to the non-blocking features provided by Mojolicious, allowing you to do 10k+ simultaneous requests.
