### ISSUE TITLE
Boolean coercion doesn't work for 1 and 0

### ISSUE THREAD

**Issue by CRielsky** [jhthorsen/json-validator#39]
The attached script dies with the following errors: `/boolean2: Expected boolean - got number. /boolean1: Expected boolean - got number. at json_validator_script.pl line 21.`
Is this JSON::Validator's expected behavior or a bug?
[json_validation_script.txt](https://github.com/jhthorsen/json-validator/files/702821/json_validation_script.txt)

**Comment by jhthorsen** [comment]
This is by design. The only coerced values are "true" and "false".

I'm not sure if I want to change it or not. I guess I kind of want, since I already have this code: https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator/OpenAPI.pm#L79-L81

Please join the #swagger channel on irc.perl.org or make a killer argument here if you want a change.

The problem is that there's already a test that proves the behaviour: https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator/OpenAPI.pm#L79-L81

**Comment by CRielsky** [comment]
Can you explain the design decision? It just doesn't make much sense to me because generally 1 and 0 are viewed as indications of true and false, respectively.
