### ISSUE TITLE
Accommodating default values?

### ISSUE THREAD

**Issue by sharphosting** [jhthorsen/json-validator#55]
I am wondering if there is any possibility of accommodating default values from schemas? It's [in the spec](http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.2), but from what I understand not generally implemented.

Assuming this is not currently implemented, which I don't believe it to be, it would of course mean that the validator would need to modify the data it was validating, to add the default values to it, which would not work in all cases. Validating a string would not make sense for the default values to be added to that string. It only really seems to make sense as an option when validating a data structure. So perhaps it is out of scope for JSON::Validator.

I'm not sure how it could best be implemented, perhaps there could be an option for this. Just putting the idea out there as it's a feature I've found useful in the past with XML Schemas and would be able to make use of from JSON Schemas if the option were available.

Perhaps it would need its own module (JSON::Validator::Bleh?), that would load some JSON, validate it against a schema and return a data structure with default values included where appropriate. If there are any other features of JSON Schema that require augmenting the data, it could be a place for them too.

**Comment by jhthorsen** [comment]
You're absolutely right! This is awful, and I'm not sure how to fix it... It's very weird, since I thought this worked, since I've been using "default" with OpenAPI for so long, but I notice now, that it's only working on top level: https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator/OpenAPI.pm#L90

I do believe this should "just work", but I ran into some issues trying to fix it, because of oneOf rules and probably others. See 99094b6 for more details.

Any help is greatly appreciated.

**Comment by sharphosting** [comment]
Thanks for this. Had a look and started getting my head round things a bit. Will have another look soon and see if I can offer any assistance.

One thing I notice is that something is off on the current handling of `default` in OpenAPI, as in [that last elsif](https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator/OpenAPI.pm#L94) is never going to execute, since the case it covers is already accepted by the one above it that you mentioned.

**Comment by jhthorsen** [comment]
You're absolutely right.

I might be a bit closer in 3e351f1 / https://github.com/jhthorsen/json-validator/compare/bug/default-value, but `t/openapi-set-request.t` still fails when validation the OpenAPI spec:

```
t/openapi-set-request.t .. Invalid schema:
/paths/~1echo~1{whatever}/get/responses/200: oneOf failed: All of the oneOf rules match. Properties not allowed: schema, description. at lib/JSON/Validator/OpenAPI.pm line 28.
	JSON::Validator::OpenAPI::load_and_validate_schema(JSON::Validator::OpenAPI::Mojolicious=HASH(0x7fef7d30aac8), "data://main/echo.json", HASH(0x7fef7d30ae28)) called at Mojolicious/Plugin/OpenAPI.pm line 34
	Mojolicious::Plugin::OpenAPI::register(Mojolicious::Plugin::OpenAPI=HASH(0x7fef7d30ab88), Mojolicious::Lite=HASH(0x7fef7cf39cf0), HASH(0x7fef7a014f88)) called at Mojolicious/Plugins.pm line 46
	Mojolicious::Plugins::register_plugin(Mojolicious::Plugins=HASH(0x7fef7cf411f8), "OpenAPI", Mojolicious::Lite=HASH(0x7fef7cf39cf0), HASH(0x7fef7a014f88)) called at Mojolicious.pm line 186
	Mojolicious::plugin(Mojolicious::Lite=HASH(0x7fef7cf39cf0), "OpenAPI", HASH(0x7fef7a014f88)) called at Mojolicious/Lite.pm line 46
	main::plugin("OpenAPI", HASH(0x7fef7a014f88)) called at t/openapi-set-request.t line 22
Dubious, test returned 2 (wstat 512, 0x200)
```

Note that you need to run the test multiple times to make it fail.

**Comment by mrenvoize** [comment]
From IRC Logs.. seems my memory of this being submitted as a github issue once before was wrong.. it's just in the IRC logs:

>[2017-02-02 09:45:20] <kwa> I'm looking at fixing the implementation of the default keyword in JSON::Validator. It seems the priority is wrong. If JSON::Validator honours the default at https://github.com/jhthorsen/json-validator/blob/master/t/openapi.t#L42-L46 then L65 wouldn't be missing the huntingSkill property, right?
[2017-02-02 09:47:09] <kwa> I briefly spoke about this with Lee in #mojo a few days ago. It seems my interpretation of the default metakeyword might be wrong. It could be more "something else should use the default keyword if the value isn't set for X", rather than the validator munging the data. Keeping the data immutable makes sense.
[2017-02-02 09:47:49] <kwa> But https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator.pm#L596-L598 looks like it's trying to set the default, so the data instance is kinda mutable as it stands.
[2017-02-02 09:49:31] <Lee> my response was that the "default" falls under the metadata keywords part of the JSON Schema spec so not sure if it's something that should be used in validation and/or it's somewhat handwavy
[2017-02-02 09:50:05] <kwa> Yeah. Not sure if it should be removed from Data::Validation in that case?
[2017-02-02 09:50:18] <Lee> batman, ashimema ^^
[2017-02-02 09:50:37] <kwa> Other implementations on CPAN seem to shy away from the default keyword.
[2017-02-02 09:53:15] <kwa> Even the official test sweet leaves a bit of ambiguity to my fully understanding it https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/master/tests/draft4/default.json#L43-L45

**Comment by mrenvoize** [comment]
There's a bunch more to that conversation.. I have IRC logs for anyone interested..

But.. I think we came to the conclusion that the default keyword in json-schema isn't especially clear as to it's meaning.. and it also felt like the meaning was different to the same keyword in openapi spec.

I think there's more to this than we're currently reading into.

**Comment by jhthorsen** [comment]
How is it different from the OpenAPI spec?

**Comment by mrenvoize** [comment]
The JSON Schema description of the keyword: 
> This keyword can be used to supply a default JSON value associated with a particular schema. It is RECOMMENDED that a default value be valid against the associated schema.
The OpenAPI description of the keyword:
>Declares the value of the parameter that the server will use if none is provided, for example a "count" to control the number of results per page might default to 100 if not supplied by the client in the request. (Note: "default" has no meaning for required parameters.) See http://json-schema.org/latest/json-schema-validation.html#anchor101. Unlike JSON Schema this value MUST conform to the defined type for this parameter.

So the OpenAPI definition requires that the default value matches the type for validation, whereas the JSON Schema definition 'recommends' but does not require it.

**Comment by mrenvoize** [comment]
More from the IRC logs:

>[2017-02-06 09:57:22] <kwa> ashimema: Seems like the discussion on the default keyword has been throughly discussed. https://github.com/json-schema-org/json-schema-spec/issues/238 and https://github.com/json-schema-org/json-schema-spec/issues/204
[2017-02-06 09:58:00] <kwa> It's of my opinon that default needs to be removed from the core JSON::Validator, and maybe reimplemented in the OpenAPI module.
[2017-02-06 10:03:36]  * Lee agrees

I think I agree with this as a concept.. data going into the validator should be immutable by default and one should rely on 'plugins' to step outside of that immutable concept.

**Comment by leejo** [comment]
What @mrenvoize said - I recall the conversation in IRC and we agreed that the input data should be immutable, otherwise you're on the slippery slope to a nightmare of action at a distance and long debugging sessions. Any setting of defaults should be handled either by the downstream application code or some sort of plugin.

**Comment by jhthorsen** [comment]
I'm not sure if I agree that the data should be immutable. When is "slippery slope to a nightmare of action at a distance and long debugging sessions" true @leejo? Can you give me an example?

I would very much like default values to work, seeing this from an OpenAPI perspective.

**Comment by leejo** [comment]
@jhthorsen - If the json you receive in your app is not the json sent by the client, and its content is changed by third party code, that's action at a distance. Just think of all the fun we have with character encoding because it gets mangled somewhere between input and output - same principle.

If you're going to substitute in default values, making the json struct mutable, you need to make this *very* clear in any documentation or defer it to something that makes it clear, because otherwise it's breaking the rule of least surprise - I expect a validator to validate something, not change it.

(Admittedly this feels like a problem of ambiguity/scope creep in the JSON Schema, as per the referenced issues above)

**Comment by mrenvoize** [comment]
I think in OpenAPI the intention is much clearer regarding the default keyword.  They've both specified 'what' it does and defined restrictions on it such that it must be a 'valid' value.

Also, OpenAPI is more of an api description system, rather than a simple data validator so I think it makes sense to handle default there..

However I'm still keen to keep the core Validator immutable by default and thus not handle the 'default' keyword as it's meaning is somewhat more ambigious.  Personally.. it's two issues.. one for Validator, one for OpenAPI

**Comment by leejo** [comment]
Honestly I'm just playing devil's advocate here, we don't use default in any of our OpenAPI specs.

**Comment by jhthorsen** [comment]
@leejo: That Iiw actually my point. If you don't use "default", then you won't be surprised, but I must say I'm surprised that "default" is not used.

When that is said, I don't use "default" either...

**Comment by jhthorsen** [comment]
What about validate_and_set_default()? If we add such a method, should M::P::OpenAPI use that as default, or just validate()?

**Comment by mrenvoize** [comment]
Should we take the OpenAPI definition of default or the json schema definition ;)

I would say use validate_and_set_default in OpenAPI.. but also on the validation of the openapi spec we should fail a spec where the value of the default does not match the type of the value it's defaulting..

**Comment by sharphosting** [comment]
For my part, `validate_and_set_defaults` seems a good solution. Setting defaults really seems to be something that should be done while parsing, if it's going to 'just work'. But since we're validating an existing structure, it should not be mutated without that being explicit.

It makes no sense to me to allow invalid default values (invalid values aren't allowed, so why should default ones be allowed to be?) but perhaps to honour the spec we could offer an option on `validate_and_set_defaults` to allow them, but have it off by default. This seems to honour 'recommended'.

It seems a shame to me that defaults are not used more often. They must be in use as a concept, but simply being implemented by applications rather than put in the specs. This seems to be a loss to the specs, as they are not fully describing themselves. The reason they are not used more often seems to be mostly because they are not implemented, which seems to be mostly due to this issue of them being a different paradigm to the rest of a schema (mutating the data). It's a gnarly one, I agree. But it would be a shame if we shy away from implementation as so many others are doing, when it is a valid aspect of a schema. Finding a solid implementation will encourage others to do the same.

But again really I think it should all happen during parsing. If the schema is provided as part of the original data, default values can be added during parsing and validation, so everything is done before the app first gets its hands on it. Then it's not mutating the data, as the data itself is pointing to the schema, and defaults are being added while it is prepared. So in that case, I think it should be the default method of processing. AFAIK that's not something JSON::Validator does at the moment, it only validates after parsing has been done separately. If validation is being done on data which has already been parsed, then I think it should only happen explicitly as discussed here.

**Comment by jhthorsen** [comment]
I don't think I will validate the default value, since it's only recommended to do so. I will simply put the default value into the place where the key is missing. That also means that `{"foo":null}` will not get the default value, while `{}` will get the default value for "foo".

I don't like the method name `validate_and_set_defaults()`. Any other suggestions?

I don't mind if the data is mutated, as long as it's according to spec.

**Comment by leejo** [comment]
> I don't like the method name validate_and_set_defaults(). Any other suggestions?

`validate_with_defaults`? Make validate take an options hash?

**Comment by sharphosting** [comment]
Making validate take an options hash sounds good to me. No need for a separate method.

**Comment by jhthorsen** [comment]
Unfortunately I'm not going to look at this myself. Please open a PR if you have an idea for how this should be solved.
