### ISSUE TITLE
Why is "type":"any" supported?

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/json-validator#83]
This is a possible bug. I need to figure out why type "any" is supported by JSON::Validator. Can it be that the json-schema draft4 have been changed..?

```
$ curl -s http://json-schema.org/draft-04/schema | grep -A1 '"simpleTypes"'
        "simpleTypes": {
            "enum": [ "array", "boolean", "integer", "null", "number", "object", "string" ]
```

I also can't find it in the OpenAPI spec.

Should I remove support for "any"?

**Comment by mohawk2** [comment]
If it's not in the spec, and in any case, I can't see it really adds value. I claim it should be removed.

**Comment by akarelas-pt** [comment]
But it needs to be replaced by the ability to not declare a type (or any rules at all), like the schema permits.

So:
`    {type: "any"}`
should become:
`    {}`

Otherwise one would have to type: `{type: ["array", "boolean", "null", "number", "object", "string"]}`

(Right now the library returns an error if the schema is `{}`)

**Comment by mohawk2** [comment]
On @akarelas-pt 's point, I agree. If the spec allows empty schema, so should `JSON::Validator`.

**Comment by jhthorsen** [comment]
I'm closing this, since I don't see the harm with keeping it.

@akarelas-pt: Please open another issue if `{}` is not supported.
